#!/bin/sh
if ! [ -x "$(command -v clang-format)" ]
then
  echo 'Error: clang-format is not installed. Exiting.' >&2
  exit 1
fi

find . \( -name '*.c' -o -name '*.h' \) -exec clang -i {} -style=file:.clang-format \;

for STAGED in $(git diff --name-only --cached) 
do
	git add "$STAGED"
done